
# Configuration for the Headplane server and web application
server:
    host: "127.0.0.1"
    port: "__HEADPLANE_PORT__"

    # The secret used to encode and decode web sessions
    # Ensure that this is exactly 32 characters long
    cookie_secret: "__KEY__"

    # Should the cookies only work over HTTPS?
    # Set to false if running via HTTP without a proxy
    # (I recommend this is true in production)
    cookie_secure: true

# Headscale specific settings to allow Headplane to talk
# to Headscale and access deep integration features
headscale:
    # The URL to your Headscale instance
    # (All API requests are routed through this URL)
    url: "__HEADSCALE_URL__"

    # Optional, public URL if they differ
    # This affects certain parts of the web UI
    # public_url: "https://headscale.example.com"

    # Path to the Headscale configuration file
    # This is optional, but HIGHLY recommended for the best experience
    # If this is read only, Headplane will show your configuration settings
    # in the Web UI, but they cannot be changed.
    config_path: "/var/www/headscale/config.yaml"

    # Headplane internally validates the Headscale configuration
    # to ensure that it changes the configuration in a safe way.
    # If you want to disable this validation, set this to false.
    config_strict: true

# Integration configurations for Headplane to interact with Headscale
# Only one of these should be enabled at a time or you will get errors
integration:
    # Proc is the "Native" integration that only works when Headscale and
    # Headplane are running outside of a container. There is no configuration,
    # but you need to ensure that the Headplane process can terminate the
    # Headscale process.
    #
    # (If they are both running under systemd as sudo, this will work).
    proc:
        enabled: false

# OIDC Configuration for simpler authentication
# (This is optional, but recommended for the best experience)
#oidc:
#    issuer: "https://accounts.google.com"
#    client_id: "your-client-id"
#    client_secret: "<your-client-secret>"
#    disable_api_key_login: false
#    token_endpoint_auth_method: "client_secret_post"

    # If you are using OIDC, you need to generate an API key
    # that can be used to authenticate other sessions when signing in.
    #
    # This can be done with `headscale apikeys create --expiration 999d`
#    headscale_api_key: "<your-headscale-api-key>"

    # Optional, but highly recommended otherwise Headplane
    # will attempt to automatically guess this from the issuer
    #
    # This should point to your publicly accessibly URL
    # for your Headplane instance with /admin/oidc/callback
#    redirect_uri: "http://localhost:3000/admin/oidc/callback"
