#!/bin/bash
source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

key=$(ynh_string_random --length=16)

#checking for hedscale user
check_headscale_user

#=================================================
# INSTALL DEPENDENCIES
#=================================================
ynh_script_progression "Installing dependencies..."

ynh_nodejs_install

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd

yunohost service add "$app" --description="A short description of the app" --log="/var/log/$app/$app.log"

#=================================================
# INSTALL Headplane
#=================================================
ynh_script_progression --message="Building $app... (this will take some time and resources!)"

pushd $install_dir
    ynh_hide_warnings corepack enable && corepack prepare pnpm@latest --activate
    ynh_hide_warnings pnpm install
    ynh_hide_warnings pnpm build
popd

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression --message="Adding a configuration file..."

ynh_config_add --template="env" --destination="$install_dir/.env"

usermod -aG headscale $app
chown -R $app:$app "$install_dir"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting a systemd service..."

ynh_systemctl --service=$app --action="start" --log_path="systemd"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
