#!/bin/bash

source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

if ynh_hide_warnings yunohost service status $app >/dev/null; then
	yunohost service remove $app
fi

ynh_config_remove_systemd

ynh_config_remove_nginx

#=================================================
# UNREGISTER FROM HEADSCALE
#=================================================
ynh_script_progression "Unregistering from $headscale..."

node_id=$(yunohost app shell $headscale <<< "./headscale nodes list -o json | jq '.[]|select(.name == \"headplane-agent\").id'")
[ ! -z $node_id ] && yunohost app shell $headscale <<< "./headscale nodes delete --force -i $node_id"
yunohost app shell $headscale <<< "./headscale user destroy --force --name $app"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
