#!/bin/bash

source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

get_headscale_settings

#=================================================
# RESTORE THE APP MAIN DIR
#=================================================
ynh_script_progression "Restoring the app main directory..."

ynh_restore "$install_dir"

! ynh_in_ci_tests && usermod -aG $headscale $app
chown -R $headscale:$app "$install_dir"
chown -R $headscale:$app "$data_dir"

#=================================================
# SETUP DEX FOR OIDC
#=================================================

setup_dex

#=================================================
# SETUP HEADPLANE AGENT
#=================================================

setup_agent

#=================================================
# RESTORE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Restoring system configurations related to $app..."

ynh_restore "/etc/systemd/system/$app.service"
systemctl enable $app.service --quiet

ynh_restore "/etc/nginx/conf.d/$domain.d/$app.conf"

yunohost service add $app --description="Advanced UI for Headscale" --log="/var/log/$app/$app.log"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start" --log_path="systemd" --wait_until="Running on 127.0.0.1" --timeout=30

ynh_systemctl --service=nginx --action=reload

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Restoration completed for $app"
